version: '3.8'

services:
  iwannaberich:
    image: iwannaberich:latest
    container_name: iwannaberich
    restart: unless-stopped
    volumes:
      - ./data:/app/data # Persistence for lottery history
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.iwannaberich.rule=Host(`iwannaberich.antoniotirado.com`)"
      - "traefik.http.routers.iwannaberich.entrypoints=websecure"
      - "traefik.http.routers.iwannaberich.tls.certresolver=myresolver"
      - "traefik.http.services.iwannaberich.loadbalancer.server.port=8501"

networks:
  proxy:
    external: true
